{
	"version": 1590087717,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/canon-sheet0.png",
		"images/spwanpoint-sheet0.png",
		"images/bullet-sheet0.png",
		"images/enemy-sheet0.png",
		"images/enemy-sheet1.png",
		"images/enemy-sheet2.png",
		"images/enemy-sheet3.png",
		"images/enemy-sheet4.png",
		"images/shot-sheet0.png",
		"images/shot-sheet1.png",
		"images/menu-sheet0.png",
		"images/shake-sheet0.png",
		"images/replay-sheet0.png",
		"images/home-sheet0.png",
		"images/powerup-sheet0.png",
		"images/powerup-sheet1.png",
		"images/powerupbar-sheet0.png",
		"images/powerupbarblack-sheet0.png",
		"images/leveldeclare-sheet0.png",
		"images/backg0round-sheet0.png",
		"images/start-sheet0.png",
		"images/sound-sheet0.png",
		"images/sound-sheet1.png",
		"images/level.png",
		"images/background-sheet0.png",
		"images/bunker-sheet0.png",
		"images/damagedtank-sheet0.png",
		"images/smoke.png",
		"images/smallrighttank-sheet0.png",
		"images/buttonholder-sheet0.png",
		"images/bigbarrel-sheet0.png",
		"images/smallbarrel-sheet0.png",
		"images/explosion-sheet0.png",
		"images/explosion-sheet1.png",
		"images/explosion-sheet2.png",
		"images/close-sheet0.png",
		"images/tutorial-sheet0.png",
		"images/tutorial-sheet1.png",
		"images/scoreicon-sheet0.png",
		"images/highscoreicon-sheet0.png",
		"images/maskpowerupbar-sheet0.png",
		"images/powerup2-sheet0.png",
		"images/powerup2-sheet1.png",
		"images/spwanpoint1-sheet0.png",
		"images/smallmissile-sheet0.png",
		"images/smallmissile-sheet1.png",
		"images/taptoplay-sheet0.png",
		"images/smallenemy-sheet0.png",
		"images/music-sheet0.png",
		"images/music-sheet1.png",
		"images/howtoplay-sheet0.png",
		"images/loadingtext-sheet0.png",
		"images/medal-sheet0.png",
		"images/smokemissile.png",
		"images/bombshell-sheet0.png",
		"images/mazzle-sheet0.png",
		"images/next-sheet0.png",
		"images/splash-sheet0.png",
		"images/scorefactor.png",
		"images/plusscore-sheet0.png",
		"images/levelmodeended-sheet0.png",
		"images/tutorialfixed-sheet0.png",
		"images/pointer-sheet0.png",
		"media/tank explosion.m4a",
		"media/tank explosion.ogg",
		"media/cannon+2.m4a",
		"media/cannon+2.ogg",
		"media/rocket-shoot.m4a",
		"media/rocket-shoot.ogg",
		"media/click.m4a",
		"media/click.ogg",
		"media/bg sound 1.m4a",
		"media/bg sound 1.ogg",
		"media/gameplay music.m4a",
		"media/gameplay music.ogg",
		"media/menu music.m4a",
		"media/menu music.ogg",
		"media/miss shoot.m4a",
		"media/miss shoot.ogg",
		"media/tank explotion.m4a",
		"media/tank explotion.ogg",
		"media/best high score.m4a",
		"media/best high score.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}